### ISSUE TITLE
BYON pipelines installation can be configured based on requirements [Admin]

### ISSUE THREAD

**Issue by pacospace** [open-services-group/byon#12]
As Platform Operator,

I want to have a way to configure the deployment of BYON pipelines.

**Comment by pacospace** [comment]
- [ ] Identify requirements to be configured (e.g. minimum resources for builds, username/password for Registry Push)

**Comment by codificat** [comment]
Should this be included into #11 as part of the acceptance criteria? I.e. that I can provide the configuration at install time

**Comment by pacospace** [comment]
> Should this be included into #11 as part of the acceptance criteria? I.e. that I can provide the configuration at install time

#11 is the base for installing with default values using `helm`, then in this issue we extend that to have configurable values, users/admin are interested in, for the templates for example with the CLI. wdyt?

**Comment by codificat** [comment]
I understand the idea. However, I believe some configuration is mandatory: having credentials for external registries is a pre-requisite for the pipelines to be able to push to them; similarly, a token is needed to interact with GitHub.

Or should we aim to have a self-contained deployment option that only uses cluster-internal resources and requires no configuration at all?

**Comment by pacospace** [comment]
> I understand the idea. However, I believe some configuration is mandatory: having credentials for external registries is a pre-requisite for the pipelines to be able to push to them; similarly, a token is needed to interact with GitHub.
> 
Yes agree, so let's have a list first of mandatory and then one for possible configuration requirements, wdyt? 

> Or should we aim to have a self-contained deployment option that only uses cluster-internal resources and requires no configuration at all?

**Comment by tumido** [comment]
@pacospace @codificat is this still relevant?
