### ISSUE TITLE
BYON Pipelines can be installed as Operator from Operator Hub [Admin]

### ISSUE THREAD

**Issue by pacospace** [open-services-group/byon#13]
As Platform  Operator,

I want to install BYON Pipelines from Operator Hub.

Ref: https://labs.consol.de/development/2021/05/03/helm_based_operator.html

**Comment by pacospace** [comment]
Depends-On: https://github.com/open-services-group/byon/issues/11

**Comment by tumido** [comment]
Closing, if we have a need for this in future we can reopen
