### ISSUE TITLE
Define new image tag annotations

### ISSUE THREAD

**Issue by tumido** [open-services-group/byon#18]
Find agreement on new additional imagestream annotations:

| Status | Annotation key | Values | Description |
| --- | --- | --- | --- |
| Preexisting | `opendatahub.io/notebook-image-desc` | string | User facing image description |
| Proposed new | `opendatahub.io/notebook-image-message`| string encoded JSON | Validation output (errors and recommendations) |
| Preexisting | `opendatahub.io/notebook-image-name` | string | User facing image name |
| Proposed new, questionable | `opendatahub.io/notebook-image-origin` | string | Defines if the image is part of ODH distribution, admin imported or user created. Proposed values `Default`, `Admin` and `Custom` |
| Proposed new | `opendatahub.io/notebook-image-phase` | string | State of validation process: `Validating`, `Success`, `Failed` |
| Preexisting | `opendatahub.io/notebook-image-url` | url |  Container image url e.g. `quay.io/org/image:tag` |
| Proposed new | `opendatahub.io/notebook-image-visible` | boolean string | Decides if the imagestream is shown to users in spawner UI. Either `"true"` or `"false"` |

**Comment by tumido** [comment]
@lavlas, should we move this discussion into ODH or can we decide that in here?

**Comment by tumido** [comment]
@Lavlas basically all we are introducing are the annotations in the table above with status `Proposed new`, the rest is just summary of what we know about the already existing annotations that we're trying to populate during the import.

**Comment by tumido** [comment]
bump @lavlas, should I open a similar issue in the ODH? Who should we pull in for this?

**Comment by LaVLaS** [comment]
I created a linked issue in the odh-dashboard repo to reference this issue. We can track the final list of annotations in this issue since they are produced and reference this in the Dashboard documentation

**Comment by tumido** [comment]
Updated: removed `notebook-image-visible`, added `notebook-image-creator`
