### ISSUE TITLE
Define states for Pipelines and UI (e.g. validating, validated, failed)

### ISSUE THREAD

**Issue by pacospace** [open-services-group/byon#23]
**Is your feature request related to a problem? Please describe.**
UI relies on Pipelines states and therefore there is a need to agree on these states.

**Describe the solution you'd like**
Have a definition of the states required by UI and Pipelines in a doc describing what is expected and accessible at each of these states.

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
from Kyle:  https://docs.google.com/document/d/11DKHpMAvSZdxU6pl7dm3Xn4bXvwOZiG6Jolinshi_GQ/edit

**Comment by tumido** [comment]
```mermaid
stateDiagram-v2
    [*] --> Importing
    Importing --> Validating
    Validating --> Success
    Validating --> Failure
    Success --> [*]
    Failure --> [*]

    note right of Importing
        Import pipeline is scheduled but
        ImageStream was not yet created
    end note

    note left of Validating
        Import pipeline is running,
        phase can be sourced from
        ImageStream annotation
    end note
```

**Comment by tumido** [comment]
Let's conclude this as done. If we decide on further extension to this, we can reopen/revisit.
