### ISSUE TITLE
Minimal dev setup required for contribution on UI

### ISSUE THREAD

**Issue by oindrillac** [open-services-group/byon#27]
As developers planning to contribute on the byon UI development efforts, we need to determine the minimal requirements, setup, and environment required to start contributing.

UI design (working document) - https://marvelapp.com/prototype/6dcfc3h/screen/85139864

**Comment by oindrillac** [comment]
@dlabaj can you please update this issue to point to any available developer documentation which describes the setup needed for contribution to the UI?

**Comment by oindrillac** [comment]
BYON development on ODH being tracked here https://github.com/opendatahub-io/odh-dashboard/issues/121

**Comment by oindrillac** [comment]
Finalized REST API Design documentation documented here https://studio-ws.apicur.io/sharing/f34aaaa8-58e0-48fb-b36f-1d91ac5ebf48

**Comment by tumido** [comment]
I think this is resolved now.
