### ISSUE TITLE
Dashboard backend not allowing to patch name/description

### ISSUE THREAD

**Issue by tumido** [open-services-group/byon#40]
According to mocks name and description should be updateable

https://marvelapp.com/prototype/6dcfc3h/screen/85139857

![image](https://user-images.githubusercontent.com/7453394/161982368-10310e96-c97e-4a34-897a-5566e3782d09.png)

/kind bug
/assign @tumido

**Comment by oindrillac** [comment]
closing. resolved by https://github.com/opendatahub-io/odh-dashboard/pull/172
