### ISSUE TITLE
Change messaging for out of scope validation

### ISSUE THREAD

**Issue by tumido** [open-services-group/byon#42]
Change the message if the first content check fails - If python is not present it is not an `error` but rather a `warning`. Skip further validation in such cases, because the image may be R or something else totally valid.

Change the Dashboard frontend/backend to support toggling the visibility on failed images when only the messages with `warning` severity are present. Disable the visibility toggle if there are `error` messages.

**Comment by oindrillac** [comment]
@tumido Does it still make sense to check for Jupyter notebook compatibility on that image? Should it be an `error` if we cannot validate if its a valid Jupyter notebook image that is compatible with JupyterHub. Coz in that case we know it will not work.

I think we should clarify, what are the definitions that we're looking at for "Error" and "Warning". Does the following look reasonable?

- Warning: Not matching our minimum criteria, outside of our scope. Warning images can be enabled
- Error: We know that it will break. Errored images cannot be enabled.

**Comment by tumido** [comment]
Digging into it more, I actually think the scenario may never happen, because we always need to spawn the jupyterlab environment... and Jupyterlab has only python implementation... it seems Python has to be present **always** and our minimal requirements are correct and needs to be **always** met. @codificat @oindrillac @lavlas can you help me verify this assumption is correct?

**Comment by tumido** [comment]
So.. I've run this problem by @guimou and he confirmed me that all our minimal requirements must be met for **any** JH spawneable image. That means even the R/Julia/whatever images need to have Python and jupyterhub/jupyterlab packages and so on. That means if an image fails our checks we can be quite certain it's not spawneable. In that light, we should **never** allow users to enable images which failed validation.

Also important lesson that @guimou gave me here. We need to remember we're checking **compatibility** with JupyterHub spawner, not that if all the components of the image work. That means, if user wants something extra in the image to work - like R in this case, it's their responsibility to ensure that. If we were to check every combination of [possible kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) it would be really hard to implement properly and maintain.
