### ISSUE TITLE
Software annotations for additional software like R, RStudio

### ISSUE THREAD

**Issue by tumido** [open-services-group/byon#43]
During discussions with Jeff about https://github.com/open-services-group/byon/issues/42 one more feature surfaced -> It would be nice to show R/RStudio version along with Python versions. Maybe other software will come later, let's start with these two and expand the list if needed.

/assign @tumido

**Comment by oindrillac** [comment]
(Discussion from April 6, 2020 BYON WG)

It's valuable to show software included in the image along with packages.

Updates needed to UI Mockup and the changes to be made in the following places to show included software:

- [ ] Admin UI - Software Version also shown in Admin UI under Notebook Image settings along with Packages.
- [ ] Spawner UI - Show Python version under question mark in spawner UI, along with Software included. Show description under Image Name

**Comment by tumido** [comment]
@oindrillac I think what you mention in your comment should be a separate issue. This issue is focusing mainly on the BYON pipelines expansion to even detect R/Studio.

**Comment by tumido** [comment]
Resolved via https://github.com/thoth-station/helm-charts/pull/43
