### ISSUE TITLE
[2pt] Trigger notebook image build with template issue

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/byon#50]
**Is your feature request related to a problem? Please describe.**
As an ODH Admin, I want to be able to trigger a new image build by opening an issue through a template, so there is little effort on my part to trigger a build and so that the built image shows up on my Jupyter Notebook Spawner on ODH.

**Describe the solution you'd like**
I want to be able to create a Github issue using a template. This template doesn't _need_ any other input from the user and the bot will know what to do with the issue. All correspondence with the bot will be done through that issue.

**Acceptance Criteria**
- [ ] Create a template issue that has a bot assigned
- [ ] Template could have fields to provide custom parameters to the build
- [ ] We can deploy this feature/feature-branch to os-climate

**Additional context**
related to: https://github.com/open-services-group/byon/issues/49

**Comment by goern** [comment]
/close
this to focus on the ODH/RHODS focused UX (via odh-dashboard)
