### ISSUE TITLE
[8pt] Make bot respond to issues and build images

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/byon#51]
**Is your feature request related to a problem? Please describe.**
As the bot, I want to respond to an issue I am assigned to and build the repo into a custom notebook image.

**Describe the solution you'd like**
I want the bot to automatically start building the image and hosting it.

**Acceptance Criteria**
- [ ] That issue assigned to the bot triggers a new custom notebook image build
- [ ] Bot handles closing the issue if no issues arise, otherwise it uses the issue as a platform to inform the user of errors and possible avenues to correct the errors.
- [ ] Reuse BYON verification, aicoe-ci pipelines

**Additional context**
part of epic: https://github.com/open-services-group/byon/issues/49

**Comment by goern** [comment]
/close 
this to focus on the ODH/RHODS focused UX (via odh-dashboard)
