### ISSUE TITLE
[1pt] Define new ADR that “bot” is a GitHub App

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/byon#53]
**Is your feature request related to a problem? Please describe.**
Define new ADR that “bot” is a GitHub App

**Describe the solution you'd like**
I want to create an ADR that defines what a bot is in the context of this [EPIC](https://github.com/open-services-group/byon/issues/49). We are using a Github app as a bases of the bot, which will also use probot most likely.

**Describe alternatives you've considered**
Other bot considerations are github actions.

**Additional context**
related: https://github.com/open-services-group/scrum/issues/15

**Comment by goern** [comment]
I think we have concluded to pivot from a bot-driven use case, to focus on the integration with the odh-dashboard. 

is that correct?

if so, can we close this issue?

/kind documentation
/priority critical-urgent
