### ISSUE TITLE
[3pt] have the bot comment location of hosted notebook

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/byon#54]
**Is your feature request related to a problem? Please describe.**
As an ODH Admin, I want the closing of my template issue to signify that my notebook image is available on my ODH deployment via the Jupyter Notebook Spawner.

**Acceptance Criteria**

- [ ] The bot should give updates on the overall  status of the build and deployment. 
- [ ] The template issue should not close until the image is available in the spawner

**Additional context**
part of epic: https://github.com/open-services-group/byon/issues/49

**Comment by goern** [comment]
/close
this to focus on the ODH/RHODS focused UX (via odh-dashboard)
